services:
  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
    healthcheck:
      test: PGPASSWORD=password psql -e -U user -d motorway -c 'SELECT 1'
      interval: 1s
      start_period: 1m

  api:
    image: motorway-test-app-server
    init: true
    build:
      context: .
      target: motorway-test-app-server
    environment:
      - PGPASSWORD=password
      - PGUSER=user
      - PGDATABASE=motorway
      - PGHOST=localhost
    ports:
      - 3000:3000
