services:
  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
    healthcheck:
      test: PGPASSWORD=password psql -e -U user -d motorway -c 'SELECT 1'
      interval: 1s
      start_period: 1m
